-- Tic-Tac-Toe Arena Supabase schema
-- Run this in your Supabase SQL editor before enabling online matchmaking.

create table if not exists public.players (
  id text primary key,
  name text not null,
  wins_online integer not null default 0,
  losses_online integer not null default 0,
  draws_online integer not null default 0,
  wins_bot integer not null default 0,
  losses_bot integer not null default 0,
  draws_bot integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.games (
  id text primary key,
  player_x_id text not null,
  player_x_name text not null,
  player_o_id text,
  player_o_name text,
  mode text not null check (mode in ('local', 'bot', 'online')),
  bot_difficulty text,
  board text not null default '---------',
  turn text not null default 'X' check (turn in ('X', 'O')),
  winner text check (winner in ('X', 'O', 'draw') or winner is null),
  status text not null default 'active' check (status in ('waiting', 'active', 'finished', 'abandoned')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_move_at timestamptz not null default now()
);

create table if not exists public.matchmaking_queue (
  id bigint generated by default as identity primary key,
  player_id text not null unique,
  player_name text not null,
  game_id text,
  joined_at timestamptz not null default now()
);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  game_id text not null,
  sender_id text not null,
  sender_name text not null,
  message text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_games_status on public.games(status);
create index if not exists idx_games_player_x on public.games(player_x_id);
create index if not exists idx_games_player_o on public.games(player_o_id);
create index if not exists idx_matchmaking_joined_at on public.matchmaking_queue(joined_at);
create index if not exists idx_matchmaking_game_id on public.matchmaking_queue(game_id);
create index if not exists idx_chat_messages_game_created on public.chat_messages(game_id, created_at);

-- This app routes all database writes through server-side Next.js API routes using SUPABASE_SECRET_KEY.
-- If you later access these tables directly from the browser, enable RLS and add policies carefully.
